# NumPy Array

### Import Numpy

In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]

In [3]:
type(my_list)

list

### Create a Vector - 1D Array

In [4]:
arr = np.array(my_list)

In [5]:
type(arr)

numpy.ndarray

### Create a Matrices - 2D Array

In [6]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Create a array using NumPy

### 1. arange()

In [9]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### 2. Zeros

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### 3. Ones

In [13]:
np.ones(3)

array([1., 1., 1.])

In [14]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

### 4. linspace

In [15]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [16]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

### 5. Identical matrices

In [17]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 6. Random

In [18]:
np.random.rand(5)

array([0.72484605, 0.08784392, 0.83262716, 0.4946623 , 0.93113903])

In [19]:
np.random.rand(5,5)

array([[0.62081521, 0.87320132, 0.52110531, 0.43780843, 0.95873438],
       [0.98252609, 0.39635565, 0.18193627, 0.0868733 , 0.82316884],
       [0.74496018, 0.62460647, 0.34343464, 0.71563182, 0.77371028],
       [0.30330615, 0.13402267, 0.95284687, 0.06347446, 0.43238665],
       [0.50581377, 0.1775089 , 0.51275394, 0.0111899 , 0.57962066]])

In [20]:
np.random.randn(2)

array([ 0.59114544, -0.51011238])

In [21]:
np.random.randn(2,2)

array([[-0.65447959, -0.72917398],
       [-1.83441173, -0.70488366]])

### 7. Int

In [22]:
np.random.randint(1,50)

48

In [23]:
np.random.randint(1,50,10)

array([28, 11,  8, 25, 20, 15, 49, 12,  3, 30])

### Reshape

In [24]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [25]:
new_arr = arr.reshape(5,5)
new_arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### Shape of array

In [26]:
arr.shape

(25,)

In [27]:
new_arr.shape

(5, 5)

### Datatype in array

In [28]:
arr.dtype

dtype('int32')

### Max value

In [29]:
arr.max()

24

In [30]:
arr.argmax()

24

### Min value

In [31]:
arr.min()

0

In [32]:
arr.argmin()

0

### Mean value

In [33]:
arr.mean()

12.0

### Sum value

In [34]:
arr.sum()

300

# Indexing

In [35]:
arr = np.arange(0,11)

In [36]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
arr[5]

5

In [38]:
arr[5:9]

array([5, 6, 7, 8])

In [39]:
arr[8:]

array([ 8,  9, 10])

In [40]:
arr[:5]

array([0, 1, 2, 3, 4])

## Create a copy

In [41]:
slice_arr = arr[1:5]

In [42]:
slice_arr[:] = 100

In [43]:
slice_arr

array([100, 100, 100, 100])

In [44]:
arr

array([  0, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [45]:
arr_copy = arr.copy()

In [46]:
arr_copy[:] = 101

In [47]:
arr_copy

array([101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101])

In [48]:
arr

array([  0, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

# Selection

In [49]:
selection_arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [50]:
selection_arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
selection_arr.shape

(3, 3)

In [52]:
selection_arr[0,0]

1

In [53]:
selection_arr[1,1]

5

In [54]:
selection_arr[1,2]

6

In [55]:
selection_arr[:2,:3]

array([[1, 2, 3],
       [4, 5, 6]])

# NumPy Math Operations

In [56]:
arr = np.array([1,2,3,4,5])

In [57]:
arr

array([1, 2, 3, 4, 5])

### Addition

In [58]:
arr + arr

array([ 2,  4,  6,  8, 10])

### Subtraction

In [59]:
arr - arr

array([0, 0, 0, 0, 0])

### Multiplication

In [60]:
arr * arr

array([ 1,  4,  9, 16, 25])

In [61]:
arr * 10

array([10, 20, 30, 40, 50])

### Division

In [62]:
arr / arr

array([1., 1., 1., 1., 1.])